spring.application.name=ai-insurance-fraud-detection

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_claims
spring.datasource.username=postgres
spring.datasource.password=Amar@10789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=AIzaSyDkx1IC3DFbIv12oghcLyFTeiWN0ZBinOw